/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TaiKhoanDAO;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.TaiKhoan;

/**
 *
 * @author dinhv
 */
public class FromDoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form FromDoiMatKhau
     */
    public FromDoiMatKhau() {
        this.setUndecorated(true);
        initComponents();

        setColor(txtmatkhaucu);
        setColor(txtmatkhaumoi);
        setColor(txtnhaplaimatkhaumoi);
        setLocation(632, 158);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void setColor(JTextField txt) {
        txt.setBackground(new Color(0, 0, 0, 0));
    }

    public void dangNhap() {
        this.setVisible(false);
    }

    public boolean kiemTraTrong(String txt) {
        Matcher checknull = Pattern.compile("^\\s*$").matcher(txt);
        return checknull.matches();
    }

    public void kiemTraPassword() {
        String passNew1 = new String(txtmatkhaumoi.getPassword());
        String passNew2 = new String(txtnhaplaimatkhaumoi.getPassword());
        if (kiemTraTrong(txtmatkhaucu.getText()) || kiemTraTrong(passNew1) || kiemTraTrong(passNew2)) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ dữ liệu");
            return;
        }
        TaiKhoan tk = new TaiKhoanDAO().selectById(new TaiKhoan());
        if (!(txtmatkhaucu.getText().equalsIgnoreCase(tk.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không chính xác");
            return;
        }
        if (!(passNew1.equals(passNew2))) {
            JOptionPane.showMessageDialog(this, "Nhập lại mật khẩu mới không chính xác");
            return;
        }
        new TaiKhoanDAO().update(tk, passNew2);
        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        txtmatkhaucu = new javax.swing.JTextField();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btndoimatkhau = new com.k33ptoo.components.KButton();
        txtnhaplaimatkhaumoi = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btndoimatkhau1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 204));

        txtmatkhaucu.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtmatkhaucu.setForeground(new java.awt.Color(255, 255, 255));
        txtmatkhaucu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtmatkhaucu.setCaretColor(new java.awt.Color(255, 255, 255));

        txtmatkhaumoi.setBackground(new java.awt.Color(255, 255, 255));
        txtmatkhaumoi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtmatkhaumoi.setForeground(new java.awt.Color(255, 255, 255));
        txtmatkhaumoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtmatkhaumoi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmatkhaumoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatkhaumoiActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Mật khẩu mới");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Mật khẩu cũ");

        btndoimatkhau.setText("Đổi mật khẩu");
        btndoimatkhau.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btndoimatkhau.setkBackGroundColor(new java.awt.Color(24, 96, 244));
        btndoimatkhau.setkBorderRadius(30);
        btndoimatkhau.setkEndColor(new java.awt.Color(24, 96, 244));
        btndoimatkhau.setkHoverEndColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndoimatkhau.setkHoverStartColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau.setkStartColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimatkhauActionPerformed(evt);
            }
        });

        txtnhaplaimatkhaumoi.setBackground(new java.awt.Color(255, 255, 255));
        txtnhaplaimatkhaumoi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtnhaplaimatkhaumoi.setForeground(new java.awt.Color(255, 255, 255));
        txtnhaplaimatkhaumoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtnhaplaimatkhaumoi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnhaplaimatkhaumoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhaplaimatkhaumoiActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nhập lại mật khẩu mới");

        btndoimatkhau1.setText("Đăng nhập");
        btndoimatkhau1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btndoimatkhau1.setkBackGroundColor(new java.awt.Color(24, 96, 244));
        btndoimatkhau1.setkBorderRadius(30);
        btndoimatkhau1.setkEndColor(new java.awt.Color(24, 96, 244));
        btndoimatkhau1.setkHoverEndColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndoimatkhau1.setkHoverStartColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau1.setkStartColor(new java.awt.Color(24, 119, 242));
        btndoimatkhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimatkhau1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtnhaplaimatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndoimatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnhaplaimatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndoimatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatkhaumoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatkhaumoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatkhaumoiActionPerformed

    private void btndoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimatkhauActionPerformed
        kiemTraPassword();
    }//GEN-LAST:event_btndoimatkhauActionPerformed

    private void txtnhaplaimatkhaumoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhaplaimatkhaumoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhaplaimatkhaumoiActionPerformed

    private void btndoimatkhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimatkhau1ActionPerformed
        dangNhap();
    }//GEN-LAST:event_btndoimatkhau1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btndoimatkhau;
    private com.k33ptoo.components.KButton btndoimatkhau1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtmatkhaucu;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JPasswordField txtnhaplaimatkhaumoi;
    // End of variables declaration//GEN-END:variables
}
